export enum AppErrorCode {
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  SERVICE_INACTIVE = 'SERVICE_INACTIVE',
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_INACTIVE = 'STAFF_INACTIVE',
  STAFF_SERVICE_UNSUPPORTED = 'STAFF_SERVICE_UNSUPPORTED',
  OUTSIDE_WORKING_HOURS = 'OUTSIDE_WORKING_HOURS',
  STAFF_TIME_OFF = 'STAFF_TIME_OFF',
  APPOINTMENT_CONFLICT = 'APPOINTMENT_CONFLICT',
  APPOINTMENT_NOT_FOUND = 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_STATUS_INVALID = 'APPOINTMENT_STATUS_INVALID',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}